package com.sri.apps.netsim; 


/**
 * Basically this class is a connection or a TCP session that is
 * generated by a host.
 * This only represents a TCP client object.  So this can be extended by
 * each protocol as we want.
 */
public abstract class PortService
{
        /**
         * The host module in which thsi service is running.
         */
    HostModule hostModule = null;

        /**
         * Port on which the service is running.
         */
    int port;

        /**
         * Tells if this service is running or not.
         */
    boolean isRunning = false;

        /**
         * Name of this service.
         */
    String serviceName = "";

        /**
         * The router interface of the host.
         */
    //NetworkInterface routerInterface = null;

        /**
         * Default constructor.
         * Shouldnt be called.
         */
    protected PortService()
    {
    }

        /**
         * Constructor.
         */
    public PortService(HostModule host, String name, int port)
    {
        this.hostModule = host;
        this.serviceName = name;
        this.port = port;
    }

        /**
         * Basically a Host calls this function
         * when it gets a packet destined to this service.
         */
    public abstract void processPacket(Packet packet)
        throws Exception;

        /**
         * Start the service.
         */
    public void start()
    {
        isRunning = true;
    }

        /**
         * Stop the service.
         */
    public void stop() throws Exception
    {
    }
}
